project_id = "qvavaxqdsbwjcimsbqmx"

[functions.tmdb-proxy]
verify_jwt = false

[functions.check-movie-availability]
verify_jwt = false

[functions.kinopoisk-proxy]
verify_jwt = false

[functions.ai]
verify_jwt = false

[functions.kinogo-parser]
verify_jwt = false

[functions.get-parsed-links]
verify_jwt = false

[functions.cleanup-expired-links]
verify_jwt = false